<%@ Page Title="Manage Project Group" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageProjectGroup.aspx.cs" Inherits="FYPMSWebsite.Student.ManageProjectGroup" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <script type='text/javascript'>
        function clearText(source) {
            source.value = "";
        }
    </script>

    <div class="form-horizontal">
        <h4><span style="text-decoration: underline; color: #00008B" class="h4"><strong>Manage Project Group</strong></span></h4>
        <asp:Label ID="lblDeleteProjectGroupMessage" runat="server" CssClass="label-info col-xs-12" Visible="false" BackColor="Transparent"></asp:Label>
        <div class="form-group">
            <asp:Panel ID="pnlGroupMembers" runat="server" Visible="false">
                <!-- Group member display -->
                <h5><span style="text-decoration: underline; color: #00008B; margin-left: 15px" class="h5"><strong>Group Members</strong></span></h5>
                <div class="col-xs-12" style="margin-bottom: 10px">
                    <asp:GridView ID="gvGroupMembers" runat="server" CssClass="table-condensed" Visible="false" BorderStyle="Solid" CellPadding="0"
                        AutoGenerateDeleteButton="false" DeleteText="Remove" OnRowDataBound="GvGroupMembers_RowDataBound" OnRowDeleting="GvGroupMembers_RowDeleting">
                    </asp:GridView>
                </div>
            </asp:Panel>
            <!-- Error/feedback messages for group member display -->
            <div class="col-xs-12">
                <div>
                    <asp:Label ID="lblGroupMembersMessage" runat="server" CssClass="label-info" Visible="false" BackColor="Transparent"></asp:Label>
                </div>
                <div>
                    <asp:Label ID="lblGroupAssignedMessage" runat="server" CssClass="label-info" Visible="false" BackColor="Transparent"></asp:Label>
                </div>
            </div>
        </div>
        <asp:Panel ID="pnlAddGroupMember" runat="server" Visible="false">
            <br />
            <h5><span style="text-decoration: underline; color: #00008B" class="h5"><strong>Add Group Member</strong></span></h5>
            <!-- Student username input -->
            <div class="form-group">
                <asp:Label runat="server" Text="Username:" CssClass="control-label col-xs-1" AssociatedControlID="txtUsername"></asp:Label>
                <div class="col-xs-2">
                    <asp:TextBox ID="txtUsername" runat="server" CssClass="form-control input-sm" MaxLength="15" Wrap="false"
                        onclick='clearText(this)' ValidationGroup="UsernameValidation"></asp:TextBox>
                </div>
                <div class="col-xs-2">
                    <asp:Button ID="btnAddGroupMember" runat="server" Text="Add Group Member" CssClass="btn-sm"
                        ValidationGroup="UsernameValidation" OnClick="BtnAddGroupMember_Click" />
                </div>
                <!-- Error/feedback messages for adding group member -->
                <div class="col-xs-offset-1 col-xs-10">
                    <asp:RequiredFieldValidator runat="server" ErrorMessage="A username is required." ControlToValidate="txtUsername"
                        CssClass="text-danger" Display="Dynamic" EnableClientScript="True" ValidationGroup="UsernameValidation"></asp:RequiredFieldValidator>
                    <asp:CustomValidator ID="CvValidateNewMember" runat="server" ErrorMessage=""
                        ControlToValidate="txtUsername" CssClass="text-danger" Display="Dynamic" EnableClientScript="True"
                        OnServerValidate="CvValidateNewMember_ServerValidate" ValidationGroup="UsernameValidation"></asp:CustomValidator>
                    <asp:Label ID="lblAddGroupMemberMessage" runat="server" CssClass="label-info" Visible="false" BackColor="Transparent"></asp:Label>
                </div>
            </div>
        </asp:Panel>
        <asp:Panel ID="pnlCreateGroup" runat="server" Visible="false">
            <!-- Create group button -->
            <div class="form-group">
                <div class="col-xs-12">
                    <asp:Button ID="btnCreateGroup" runat="server" Text="Create Group" CssClass="btn-sm" OnClick="BtnCreateGroup_Click" />
                </div>
                <div class="col-xs-12">
                    <asp:Label ID="lblCreateDeleteGroupMessage" runat="server" CssClass="label-info" Visible="false" BackColor="Transparent"></asp:Label>
                </div>
            </div>
        </asp:Panel>
    </div>
</asp:Content>
